version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${{ secrets.POSTGRES_DB }}
      - POSTGRES_USER=${{ secrets.POSTGRES_USER }}
      - POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
